apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chart-msc-time.fullname" . }}
  labels:
    {{- include "chart-msc-time.labels" . | nindent 4 }}
spec:
  {{- if .Values.statefulSet.parallel }}
  podManagementPolicy: "Parallel"
  {{- end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart-msc-time.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart-msc-time.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart-msc-time.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          volumeMounts:
          - name: config-volume
            mountPath: /app/config.json
            subPath: config.json
          {{- if .Values.commonVisits.enabled }}
          - name: visit-logs
            mountPath: /app/visits/
          {{- end }}

          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: top-token
                  key: token
          resources:
            requests:
              memory: "64M" 
              cpu: "100m" 
              #10% of overall CPU time
            limits:
              memory: "256M"
              cpu: "200m" 
              #20% of overall CPU time

          ports:
            - name: http
              containerPort: 5000
              protocol: TCP

          {{- if .Values.healthcheck.enabled }}  
          livenessProbe:
            httpGet:
              path: /
              port: http
              periodSeconds: {{ .Values.healthcheck.period }}
          readinessProbe:
            httpGet:
              path: /
              port: http
              periodSeconds: {{ .Values.healthcheck.period }}
          {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
      - name: config-volume
        configMap:
          name: config-file
      {{- if .Values.commonVisits.enabled }}
      - name: visit-logs
      {{- end }}
