version: "3"

x-logging:
  &logs
  options:
    tag: "{{.Name}}"

networks:
  loki:

services:
  python_app:
    image: andrew174194/msc_time_py:latest
    ports:
      - "80:5000"
    restart: always
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - loki
    logging: *logs

  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging: *logs

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - ./promtail.yaml:/etc/promtail/config-test.yaml
      - /mnt/docker/version-pack-data/community/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config-test.yaml
    networks:
      - loki
    depends_on:
      - loki
      - grafana
      - python_app
    logging: *logs

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    logging: *logs